// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:516556281353:web:84e0c6a40d3e7ca0254ad8',
    messagingSenderId: '516556281353',
    projectId: 'notes-fa86f',
    authDomain: 'notes-fa86f.firebaseapp.com',
    storageBucket: 'notes-fa86f.appspot.com',
    measurementId: 'G-X22LVV75TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:516556281353:android:46a71e4bcec276d2254ad8',
    messagingSenderId: '516556281353',
    projectId: 'notes-fa86f',
    storageBucket: 'notes-fa86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:516556281353:ios:7bc8c0dfefc54e28254ad8',
    messagingSenderId: '516556281353',
    projectId: 'notes-fa86f',
    storageBucket: 'notes-fa86f.appspot.com',
    iosBundleId: 'com.example.notes',
  );
}
